--- # Error handling example
- hosts: apacheweb
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - name: execute a command that will fail
      command: /bin/false
      ignore_errors: yes

    - name: install telnet
      yum: name=telnet state=latest

