--- # Full include task example
- hosts: apacheweb
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify that the telnet package is installed
      raw: yum list installed | grep telnet > /home/ansible/pkgs.log
      
