--- # My first YAML playbook for Ansible

- hosts: apacheweb
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - /home/ansible/ansible/playbooks/conf/copyright.yml
    - /home/ansible/ansible/playbooks/conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Install Which Package?
  tasks:
    - name: Install Apache Web Server
      yum:  name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
    - name: Install the Lynx Web Browser
      yum: name={{ pkg_name }} state=installed
  handlers:
    - name: Restart HTTPD
      service: name=httpd state=restarted
        
