--- # My first YAML playbook for Ansible

- hosts: apacheweb
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - /home/ansible/ansible/playbooks/conf/copyright.yml
    - /home/ansible/ansible/playbooks/conf/webdefaults.yml
  tasks:
    - name: Install Apache Web server
      yum: name=httpd state=installed
      notify: restart_httpd
  handlers:
    - name: restart_httpd
      service: name=httpd state=restarted
      
