--- # Notification and Handling events
- hosts: apacheweb
  remote_user: ansible
  become: yes
  gather_facts: yes
  tasks:
  - name: Install nginx web server
    yum:
      name: nginx
      state: latest
    notify:
    - Enable and start the nginx service
  handlers: 
  - name: Enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted
