--- # Until example_env
- hosts: apacheweb
  become: yes
  user: ansible
  gather_facts: no
  tasks:
    - name: Installing Apache Web server
      yum: name=httpd state=latest
    - name: Verify service status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result

