- name: Install the Apache Web Server on RedHat/CentOS
  yum:
    name: '{{ redhat_apache }}'
    state: latest
  when: "ansible_os_family == 'RedHat'"

#- name: Wait for the service to start listening on port 80
#  wait_for:
#    port: 80
#    state: started

- shell: systemctl status httpd
  register: result
  until: result.stdout.find("active (running)") != -1
  retries: 5
  delay: 5
- debug: var=result

- debug:
    msg: Need to install Telnet
  when: "ansible_os_family == 'RedHat'"
  notify: install_telnet
