--- # My first playbook
- hosts: apacheweb
  connection: ssh
  user: ansible
  become: yes
  gather_facts: no
  vars:
    playbook_version: 1.0

  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml

  tasks:
    - name: Install apache web server
      yum: name=httpd state=installed
    - name: Verify the Lynx web browser
      yum: list=lynx
      register: result
    - debug: var=result
