--- # Prompt playbook exercise
- hosts: all
  connection: ssh
  user: ansible
  become: yes
  gather_facts: no
  vars:
    playbook_version: 1.0
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which package?
      default: telnet
   
  tasks: 
    - name: Install the specified package
      yum:
        name: {{ pkgtoinstall }}
        state: installed
