--- # Tags playbook exercise
- hosts: apacheweb
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - name: Install the telnet and lynx packages
      yum:
        name: '{{ item }}'
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verify that telnet is installed
      raw: yum list installed | grep telnet > /home/ansible/logging.log
      tags:
        - logging
