- name: restart_httpd
  service:
    name: '{{ redhat_apache }}'
    state: restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes

- name: restart_apache2
  service:
    name: '{{ debian_apache }}'
    state: restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes

- name: install_telnet
  yum:
    name: telnet
    state: latest
