--- # Master playbook for AWS webservers
- hosts: aws
  user: ansible
  become: yes

  pre_tasks:
  - name: When did the ROLE start
    raw: date > /home/ansible/startofrole.log

  roles:
    - aws_webservers

  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/ansible/endofrole.log
