--- # Web Playbook
- hosts: apacheweb
  user: ansible
  become: yes

  vars_files:
  - variables/variables.yml

  tasks:
  - include: packages/packages.yml
  - include: commands/commands.yml

  handlers:
  - include: handler/handler.yml 
